SELECT 
  INVOICE.INV_ID, 
  INVOICE.TOTAL_AMOUNT, 
  INVOICE_DETAILS.QUANTITY, 
  INVOICE_DETAILS.PROD_ID 
FROM INVOICE 
JOIN INVOICE_DETAILS ON INVOICE.INV_ID = INVOICE_DETAILS.INV_ID 
ORDER BY INVOICE_DETAILS.PROD_ID;
